version: '3.9'

volumes:
  DataVolume:
    name: 'prakticum_volume'
  pgadmin-data:
    name: 'pgadmin-data'

services:
  client:
    container_name: prakticum-client
    image: prakticum-client
    volumes:
      - DataVolume:/output:rw
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        CLIENT_PORT: ${CLIENT_PORT}
    restart: always
    ports:
      - '${CLIENT_PORT}:80'
    env_file:
      - ./.env
    networks:
      - prakticum

  server:
    container_name: prakticum-server
    image: prakticum-server
    volumes:
      - DataVolume:/app/dist/client:rw
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        SERVER_PORT: ${SERVER_PORT}
    restart: always
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    env_file:
      - ./.env
    networks:
      - prakticum
    depends_on:
      - client
      - postgres
    command: ./wait-for.sh postgres:${POSTGRES_PORT} -- node /app/packages/server/dist/index.js

  postgres:
    container_name: prakticum-database
    image: postgres:14
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    env_file:
      - ./.env
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
    networks:
      - prakticum

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:7.4
    restart: always
    env_file:
      - ./.env
    ports:
      - '8080:80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - prakticum

networks:
  prakticum:
    driver: bridge
