ARG NODE_VERSION=16


FROM node:$NODE_VERSION-buster as builder

WORKDIR /app

COPY . .

RUN yarn bootstrap \
    && yarn build \
    && chmod +x utils/wait-for.sh \
    && apt update \
    && apt install -y netcat-openbsd
